### ISSUE TITLE
Implication of globals in ortools

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#105]
```python

x,y = intvar(0,3,shape=2)
p = boolvar()

s1 = SolverLookup.lookup("ortools")()

s1 += p.implies(max([x,y]) != 1)
s1.solve()
>> True

s2 = SolverLookup.lookup("ortools")()

s2 += p.implies(max([x,y]) == 1)
s2.solve()
>>  Exception: ('OR-Tools says: model invalid:', 'Enforcement literal not supported in constraint: enforcement_literal: 0 int_max { target: 4 vars: 1 vars: 2 vars: 3 }')
```

While posting the constraint in the first case, it gets split up in the following:
` [max([x,y]) == IV0, p -> IV0 != 1]`

In the second case, this does not happen as `MaxEquality` is natively supported by OR-tools.

So to answer this todo: yes :)
https://github.com/CPMpy/cpmpy/blob/b821f441f9b38613ed4221d43b59a9344837f5dc/cpmpy/solvers/ortools.py#L355

**Comment by IgnaceBleukx** [comment]
Ok, so one way to solve this is to always replace the global constraint with a new integer/boolean variable on the rhs of the implication.
Question remains: do we want a new transformation for this or can this simply be done in `_post_constraint`? Imo it would be better to put it in a new transformation, together with this code snipped that is now present in both ortools and gurobi:
https://github.com/CPMpy/cpmpy/blob/f85c8e64f0d7397887ff11d6529053d7202de620/cpmpy/solvers/ortools.py#L378-L385
@tias what do you think?

**Comment by tias** [comment]
OK, so this includes quite a number of things.

Cleanest would probably be a new generic transformation, (not in flatten itself?), that rewrites reified constraints as appropriate, e.g.:

# Case 1, Operator == BV with Operator.bool() = true
#   assume Boolean Operators 'and' and 'or' and '->' are supported by solver...
#   (-> could be rewriten to or, should be in separate transf? can discuss in Github)
# Case 2, Comparison(OP, lhs, rhs) == BV
#   assume supported by solver if lhs and rhs are const/var
#   have list of supported lhs's? such as sum and wsum...
#   in any other case (e.g. any NumExpr lhs), decompose to [aux = get_or_make_var(lhs), Comparison(OP, aux, rhs) == BV]
#   warning, this 'get_or_make_var' may only be valid for total expressions (that always have a valid result)
#   e.g. what in case of a division? the BV should also be 'false' in case the constraint fails (div by 0)...
# Case 3, Global == BV with Global.bool() = true
#   rewrite as flatten(Global.decompose() == BV)
#   XXX will this recursively flatten? can we do this transf before flatten so other transformations also applied?

Note that the 'function globals only with equality' mentioned one comment higher is also in need of a separate transformation, but it is not this one. (it is also less urgent, as it is correct in the solvers, would just be cleaner as transf).

**Comment by IgnaceBleukx** [comment]
Yes, I think it should indeed become a new transformation and not be in the `flatten` transformation. This would require to reformat the `flat normal form` definition.
We can make a non-default argument to the transformation which contains a list of operator names natively supported by the solver. If we initialize it to `[sum', 'wsum']` I think we should be covered for the most part.

**Comment by tias** [comment]
if we keep it out of flatten, then we don't need to redefine the FNF?

Yes on the supported reifications.
Here is my refined impression, looks increasingly more doable:

>   There are three types of reification (BV=BoolVar, BE=BoolExpr):
>     - BV -> BE      single implication, from var to expression
>     - BV <- BE      single implication, from expression to var
>     - BE == BV      full reification / double implication (e.g. BV <-> BE)
> # Case 1, BE is Operator (and, or, ->)
> #   assume supported, return as is
> #   could actually rewrite into list of clauses like to_cnf() does... not here (initially)
> # Case 2, BE is a GlobalConstraint
> #   DEC = BE.decompose()
> #   return DEC == BV or DEC -> BV or BV -> DEC // copy orig cons, store index of BE, overwrite in copy?
> # Case 3, BE is Comparison(OP, LHS, RHS)
> #   have list of supported lhs's? such as sum and wsum...
> #   at the very least, (iv1 == iv2) == bv has to be supported (or equivalently, sum: (iv1 - iv2 == 0) == bv)
> #   all other cases:
> #     (AUX,c) = get_or_make_var(LHS)
> #     return c+[Comp(OP,AUX,RHS) == BV] or +[Comp(OP,AUX,RHS) -> BV] or +[Comp(OP,AUX,RHS) <- BV] // copy, index of BE, overwrith lhs arg
> # XXX is this before or after flatten? looks like after... so we must flatten before returning in case2/3?

**Comment by IgnaceBleukx** [comment]
Yes, indeed after flatten. Even after `only_bv_implies`.
Decomposition of cases looks fine, I think we should have covered most of it this way
