### ISSUE TITLE
Chained inequalities

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#109]
Something that would be nice to have is automatically translating chained (in)equalities to a set of constraints.
This is supported by the Python syntax but not (yet) in CPMpy
https://docs.python.org/3/reference/expressions.html#comparisons

```python
x = intvar(lb=0, ub=5, name="x")
1 <= x <= 3
```
Output: `x <= 3`
Expected output: `[x >= 1, x <= 3]`

**Comment by sourdough-bread** [comment]
Thx @IgnaceBleukx. However, Comparison chaining is not possible with the current state of Python.
Any operation 1 <= x <= 3, will be evaluated to (1 <=x) and (x<=3) ... etc, where the "and" keyword is not overloadable yet.
See pep: https://peps.python.org/pep-0535/ ; https://peps.python.org/pep-0335/ and https://peps.python.org/pep-0532/ for more details.
