### ISSUE TITLE
Run constraint testsuite on all solvers

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#112]
When the Gurobi solver was added to the CPMpy library, tests for all flattened constraints were added in /tests/test_constraints.py.

Still to be done is running this suite on OR-tools and Minizinc solvers (and Pysat when int-to-bool is implemented)

**Comment by IgnaceBleukx** [comment]
For minizinc:
The division operator is now implemented as the float division in minizinc (`/`). This should change to the integer division `div` operator I believe. https://github.com/MiniZinc/libminizinc/issues/568

**Comment by Wout4** [comment]
we only support integer division (//), and the test_constraints test-suite is now ran on all supported solvers
