### ISSUE TITLE
Model give no solution in ortools, works in MiniZinc

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#130]
For the following model, ortools gives 0 solution, but using MiniZinc works:
```
from cpmpy import *
import numpy as np

def donald_gerald_robert_v2():
    n = 10
    x = intvar(0,9,shape=10,name="x")
    d,o,n,a,l,g,e,r,b,t = x

    carries = intvar(0,1,shape=6,name="carries")
    c1,c2,c3,c4,c5,c6 = carries

    model = Model([AllDifferent(x),
                   d + d == 10 * c1 + t,
                   c1 + l + l == 10 * c2 + r,
                   c2 + a + a == 10 * c3 + e,
                   c3 + n + r == 10 * c4 + b,
                   c4 + o + e == 10 * c5 + o,
                   c5 + d + g == 10 * c6 + r,

                   d > 0,
                   g > 0,
                   r > 0,
                   c6 == 0, # must be 0 since R is the first digit
                   ])
    
    num_solutions = 0
    while model.solve():
        num_solutions += 1
        print(x.value())

    print("num_solutions:", num_solutions)

donald_gerald_robert_v2()
```

When some of the constraints are commented out, ortools give a (wrong) solution, e.g.
```                   
                   # c2 + a + a == 10 * c3 + e,
                   # c3 + n + r == 10 * c4 + b,
                   # c4 + o + e == 10 * c5 + o,
```

Here are some other models that has the same behavior, i.e. ortools give 0 solutions but MiniZinc does.
- http://hakank.org/cpmpy/crypta.py
- http://hakank.org/cpmpy/drive_ya_nuts.py
- http://hakank.org/cpmpy/eq10.py

I'm quite sure that all these models worked with ortools in CPMPy v0.9.7, but then stopped work with the pip version of v0.9.8.

**Comment by tias** [comment]
Oh my, I got the numpy axis wrong in the bounds calculation of weighted sum : //
Now fixed, I should add tests for the bounds!

**Comment by hakank** [comment]
Thanks. Note that there's now a superfluous print() on line 336.
