### ISSUE TITLE
Creating wsums

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#137]
Weighted sums are created when they are not supposed to atm.
For example this expression throws an error:
```python
100 * (x < 5) * (5 - x) + 10 * (x - 5)
```
As cpmpy tries to convert it to a weighed sum. I think we should change the `_wsum_should` and `_wsum_make` behaviour in expressions.py for this.

This will also require some modifications to the linearize transformation however

**Comment by tias** [comment]
fixed in 968108b260e74a86251dceb9a42a05cfa76336d0 as part of #182  , not yet merged in master

**Comment by sourdough-bread** [comment]
Closing because it's fixed in https://github.com/CPMpy/cpmpy/commit/968108b260e74a86251dceb9a42a05cfa76336d0 as part of https://github.com/CPMpy/cpmpy/pull/182 

Test-case has been added.
