### ISSUE TITLE
Any suggestion about or-tools hyperparameter search 

### ISSUE THREAD

**Issue by asdqsczser** [CPMpy/cpmpy#138]
In the [docs](https://cpmpy.readthedocs.io/en/latest/solver_parameters.html), a link is recommended but broken, "We documented some of the frequent once in our [CPM_ortools API](https://cpmpy.readthedocs.io/en/latest/cpmpy/solvers/ortools.py)".

In the tutorial, three hyperparameters are recommended.

```
params = {'cp_model_probing_level': [0,1,2,3],
          'linearization_level': [0,1,2],
          'symmetry_level': [0,1,2]}
```

Can you provide more critical parameters for the CP-SAT solver of or-tools? 

Thanks.

**Comment by tias** [comment]
Hi,

I had the pleasure of having dinner with Laurent Perron from OR-Tools at a workshop today.

We went over the parameters together and he mentioned the following as those that could be worth trying.

These are rough notes, they can be mapped (in reverse order) to actual param names in the file you linked.

use branch in lp, optimize with core, search branching, bool enc level, linearization lvl, minimize core, cp model probing level, cp model presolve, clause ordering, clause partitioning, binary minimization algo, confl minimization algo, use phase saving

@wout can you add them to the docs and tool and examples/param tune notebook? Check with @IgnaceBleukx if unclear
