### ISSUE TITLE
SolverLookup.get(..).solve() does not update the model's status

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#139]
```python
from cpmpy import *
m = Model()
SolverLookup.get("ortools",m).solve()
print(m.status())                                # expected "ExitStatus.OPTIMAL" got "ExitStatus.NOT_RUN"
````

**Comment by IgnaceBleukx** [comment]
This is very unintuitive behaviour indeed.
I'll add this to the documentation.
A solver object does not store the model (nor CPMpy constraints) when called, so when calling `solve()` on the Solver object, the status of the model should not change.
Note that in general, it should suffice to only use `m.solve(solver="ortools")`. Explicitly creating a solver interface is only usefull when relying on solver-specifc features (for example [here](https://github.com/CPMpy/cpmpy/blob/master/examples/advanced/ortools_presolve_propagate.py))

**Comment by sourdough-bread** [comment]
@IgnaceBleukx did you add this to the documentation. I can't find it. Can you post a link to it here and close the question ?

**Comment by IgnaceBleukx** [comment]
I did now
