### ISSUE TITLE
Cumulative as new global constraint

### ISSUE THREAD

**Issue by g-poveda** [CPMpy/cpmpy#141]
Hi, it might be of interest to add cumulative global [constraint](https://www.minizinc.org/doc-2.3.0/en/lib-globals.html#scheduling-constraints) in cpmpy library.

it exists at least in minizinc and ortools (one using integer variable and the other interval) and is quite handful for scheduling problems with resource.

**Comment by IgnaceBleukx** [comment]
I added a proposal to implement this global constraint as a pull request.
This is certainly a helpful global constraint to have in the library
