### ISSUE TITLE
double negation of a constraint fails with ortools 

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#142]
solver: ortools
CPMpy: version v0.9.9 
commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
[minimized.zip](https://github.com/CPMpy/cpmpy/files/9850300/minimized.zip)

m = Model().from_file(minimizedFile)
m.solve(solver="ortools") # wrongly shows UNSATISFIABLE
print(m.status())

bug found while working on my master thesis.

**Comment by rubenkindt** [comment]
expected behavior visible with replacing "ortools" with "minizinc:chuffed"

**Comment by tias** [comment]
This was a pretty serious bug... only one negation was applied.

Fixing it showed that two of our convoluted testcases was actually testing for the wrong output! It seems that it normalizing it create a double negation, that triggered the bug you found.

So, another great find, thanks.

**Comment by rubenkindt** [comment]
While using (currently latest) release version v0.9.10, I find the private attribute "._value" are not always assigned correctly, can this be a (future) problem? 
The (only used) variable "grid[3,3]" has multiple assigned values in different spots. The first constraint "grid[3,3] == 7" causes a correct assignment of 7, but "grid[3,3] == 7 == 0 == 0" causes an assignment of 1.

Same input file as original report. https://github.com/CPMpy/cpmpy/files/9850300/minimized.zip
```python
from cpmpy import *

minimizedFile = "minimized"
m = Model().from_file(minimizedFile)
m.solve(solver="ortools")
print(m.status())
print(m)
correctSet = m.constraints[0].args[0]
wrongSet = m.constraints[1].args[0].args[0].args[0]
print(correctSet.name + " = " + str(correctSet._value)) # grid[3,3] = 7
print(wrongSet.name + " = " + str(wrongSet._value))     # grid[3,3] = 1
```

**Comment by tias** [comment]
I confirm that it does not happen if you write the model, but it does happen if you import/`from_file` the model.

So it is a bug in `from_file`, it seems to (re)create two distinct Python objects for the two references to the same grid[3,3] variable with the same name...

Unfortunately the `from_file` is simply `pickle.load(f)`, so we would have to dive into Python's pickling and unpickling and how to control it better...

Please open a separate bug for it, thx
