### ISSUE TITLE
negation of AllDifferent() crashes with ortools

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#143]
solver: ortools
CPMpy: version v0.9.9
commit https://github.com/CPMpy/cpmpy/commit/e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
[minimized.zip](https://github.com/CPMpy/cpmpy/files/9850404/minimized.zip)

```python 
m = Model().from_file(minimizedFile)
m.solve(solver="ortools") # crashes

#or
pos = intvar(lb=0, ub=5, shape=3, name="positions")
m = Model()
m += ~AllDifferent(pos)
m.solve("ortools") # crashes
```

expected behavior visible with replacing "ortools" with "minizinc:chuffed"

bug found while working on my master thesis.

**Comment by tias** [comment]
This was a very nice one. Did not expect it because we use reification a lot, but this took a shortcut that lead to a piece of code where we wrote in the comments that we still had to figure out how to do global constraints best there : )

Now fixed, great find!
