### ISSUE TITLE
pysat ValueError: Wrong bound

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#150]
solver: all 'pysat'-solvers
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
[minimized.zip](https://github.com/CPMpy/cpmpy/files/9995923/minimized.zip)

```python 
file= "minimized" # don't forget to unzip
m=Model().from_file(file)
m.solve(solver="pysat")
m.solve(solver="pysat:cadical") # all fail in the same manner
m.solve(solver="pysat:minisat-gh")
m.solve(solver="pysat:minisat22")
m.solve(solver="pysat:minicard")
m.solve(solver="pysat:mergesat3")
m.solve(solver="pysat:maplesat")
m.solve(solver="pysat:maplecm")
m.solve(solver="pysat:maplechrono")
m.solve(solver="pysat:lingeling")
m.solve(solver="pysat:glucose4")
m.solve(solver="pysat:glucose3")
m.solve(solver="pysat:gluecard3")
m.solve(solver="pysat:gluecard4")
```

expected behavior: 
to solve it like other solvers ('ortools'...) do

bug found while working on my master thesis.

**Comment by IgnaceBleukx** [comment]
Closing as fixed in [e02d498](https://github.com/CPMpy/cpmpy/commit/e02d4983a0cf3386534416dd3d06cbaa0b707c10)
