### ISSUE TITLE
Gurobi sometimes does not set amount of solutions and exit status correctly

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#153]
solver: gurobi
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee

Gurobi does not set the amount of solutions and exit status correctly. It does find at least one solution, but says NOT_RUN and sets its found solutions to strange numbers, (16 for the "send more ...", while OR-Tools finds 1 and 100 for the second problem while OR-Tools finds 9)

[send_most_money16650521758194163.zip](https://github.com/CPMpy/cpmpy/files/10002243/send_most_money16650521758194163.zip)
[secondExample.zip](https://github.com/CPMpy/cpmpy/files/10002251/secondExample.zip)

```python 
from cpmpy import *

file = "send_most_money16650521758194163" #don't forget to unzip
m = Model().from_file(file)
sol = m.solveAll(solver="gurobi", solution_limit=100)
print(sol)
print(m.status())

m2 = Model().from_file(file)
sol = m2.solveAll(solver="ortools", solution_limit=100)
print(sol)
print(m2.status())
```

expected behavior: 
Same number of solution like other solvers ("ortools",...) with it exitstatus not set to NOT_RUN or no solution with exitstatus to NOT_RUN

bug found while working on my master thesis.

**Comment by IgnaceBleukx** [comment]
This issue touches upon several misspecifications actually:
1) OR-tools does not support finding all optimal solutions
2) Gurobi does support finding all optimal solutions but we did not implement it correctly. The current setting will search for `all` solutions, in decreasing quality according to the objective. 
```python
x = intvar(0,2,shape=3, name="x")
m = Model(sum(x) >= 1, minimize=sum(x))
m.solveAll(solver="gurobi",solution_limit=100, display=lambda : print(x.value(), sum(x.value())))
>>[0 0 1] 1
[1 0 0] 1
[0 1 0] 1
[2 0 0] 2
...
[2 2 1] 5
[2 2 2] 6

m.solveAll(solver="ortools",solution_limit=100, display=lambda : print(x.value(), sum(x.value())))
>> [0 0 1] 1
``` 
I'll have to look into the second model more closely as it contains many constraints...
