### ISSUE TITLE
array 1-d shape assert fails with gurobi due to strange constraint, but constraint gets solved in ortools

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#155]
solver: "gurobi"
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee

A strange constraint crashes Gurobi, but not other solvers (like OR-Tools).

[minimized.zip](https://github.com/CPMpy/cpmpy/files/10002464/minimized.zip)

```python 
from cpmpy import *

file ="minimized"  # don't forget to unzip
m=Model().from_file(file)
m.solve(solver="gurobi")
```

expected behavior: 
No crash like other solvers ("ortools" ...)

bug found while working on my master thesis.

**Comment by Wout4** [comment]
this no longer crashes
