### ISSUE TITLE
Creating a circuit of 1 element crashes "ortools" and "gurobi"

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#157]
solver: "ortools" and "gurobi"
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
minizinc-python release version 0.7.0 commit {https://github.com/MiniZinc/minizinc-python/commit/a195cf63fcfbc98665d70ab64efb5424db25bd7e)

Creating a circuit of 1 element crashes both "ortools" and "gurobi".

```python 
from cpmpy import *
x = intvar(0, 1, name="x")
m=Model()
m += Circuit([x])
m.solve(solver="ortools") # same with "gurobi"
```

expected behavior: 
No crash like other solvers ("minizinc:ortools" ...).

bug found while working on my master thesis.
edit: wrong solvers in line 1

**Comment by Dimosts** [comment]
The bug appears when the "decompose" method of the expression is called, in _post_constraint(). The decompose method is called only in ortools and gurobi and that is why this happens there.

In the decompose method of Circuit, it is assumed that it contains more than one variables.
So, "order" is assumed to be an array of variables
`        order = intvar(0,n-1, shape=n) ` 
and then an index is used to define that the last one has no succesor
`order[n-1] == 0`

However, when only 1 variable is given, then n = 1, resulting in "order" not being subscriptable.

This seems an easy fix, just returning nothing when it contains only 1 (or even 0?) variable, skipping the decomposition.

**Comment by Dimosts** [comment]
Has been solved.
