### ISSUE TITLE
Translation of gurobi status 9 to CPMpy status not implemented

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#159]
solver: gurobi
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee

Found a not implemented translation exit status for Gurobi with annotations to report if found, it is an exitstatus of 9.
[minimized.zip](https://github.com/CPMpy/cpmpy/files/10010358/minimized.zip)

```python 
from cpmpy import *

file = "minimized" # don't forget to unzip
m = Model().from_file(file)
m.solve(solver="gurobi", time_limit=5) # time limit is needed
print(m.status())
```

expected behavior: 
A CPMpy status, instead of an error.

bug found while working on my master thesis.

**Comment by IgnaceBleukx** [comment]
Duplicate with issue #136. This was fixed recently. 
Improved the fix somewhat in recent commit.
