### ISSUE TITLE
Wrongly unsatisfiable problem for ortools and gurobi

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#170]
solver: all MiniZinc subsolvers
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee also happens in the latest release v0.9.10
minizinc-python release version 0.7.0 commit {https://github.com/MiniZinc/minizinc-python/commit/a195cf63fcfbc98665d70ab64efb5424db25bd7e)

The program below gives wrongly unsat when using OR-Tools and Gurobi, since the solution does exist (b=False; i=0; k=1). The solution can be found via MiniZinc and weirdly the bug does occur in all solvers when flattening the model. 
occurs both in CPMpy v0.9.9 and v0.9.10

```python
from cpmpy import *
from cpmpy.transformations.flatten_model import flatten_model

b = boolvar(name="b")
i = intvar(lb=0, ub=1, name="i")
k = intvar(lb=0, ub=1, name="k")

m = Model()
m += (b == False) & (b != (k == 1))
m += (i == 0) == (b != (k == 1))
m += i == 0

# m = flatten_model(m) # bug occurs in all solvers when flattened

m.solve(solver="minizinc:gurobi")
print(m.status())
m.solve(solver="gurobi")
print(m.status())
m.solve(solver="minizinc:ortools")
print(m.status())
m.solve(solver="ortools")
print(m.status())
```

Bug found while working on my master thesis.

**Comment by sourdough-bread** [comment]
Bug solved in pull request.

**Comment by tias** [comment]
@sourdough-bread EMilio, we might have worked on this in parallel. What pull request are you referring too?

I hope you had fixed it in the same way ; )
