### ISSUE TITLE
z3 translation bug

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#185]
```python
iv = intvar(1,9, shape=2)
Model((iv[0] == iv[1])).solve("z3") # works
Model(~(iv[0] != iv[1])).solve("z3") # should be identical, but triggers z3 exception
```

**Comment by tias** [comment]
ah, I think it literally tries to post `(iv[0] != iv[1]) == 0`, which is our way of expressing negation. Should catch the ==0 and post it as negation instead of an equality?

**Comment by Wout4** [comment]
That seems to work, I made a pull request for it (#189).
Had to make sure that we still keep some constraints as lhs == 0 if lhs is an intvar for example.
