### ISSUE TITLE
MUS tool crashes with only 1 soft constraint

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#191]
```python
from cpmpy import *
from cpmpy.tools.mus import mus

bv = boolvar()
mus(soft=[bv], hard=[~bv]) # crashes
```

Source of the error is `assum.implies(candidates)`. When `assum` is a single boolvar and candidates is a list (of length 1), it fails.

We should check when invoking `bv.implies(rhs)` rhs is either a single expression or a list of length 1, and extract this value I think. Or change to `all(candidates)` in the mus tool, but this might have some side effect by itself... to check.

**Comment by sourdough-bread** [comment]
When `assum` is a single `boolvar` and **soft** is a _list (of length 1)_, it now converts the assumption variable to a  `NDVarArray` of length 1.
