### ISSUE TITLE
minizinc: too wide error catching, test_constraints fails

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#203]
https://github.com/CPMpy/cpmpy/blob/2a5434f76b895173c8c20e58fd612e2759482262/cpmpy/solvers/minizinc.py#L173

hides multiple (almost identical) failures of the test_constraints suite (change ortools to minizinc in that file)

the real error is:
```
MiniZinc: flattening error: 
  /tmp/mzn_fragment8n0o01fp.mzn:6:
  in binary '=' operator expression
  in binary '>=' operator expression
  in binary '^' operator expression
  /home/tias/local/src/MiniZincIDE-2.5.5-bundle-linux-x86_64/share/minizinc/std/stdlib/stdlib_math.mzn:409:
  in let expression
  /home/tias/local/src/MiniZincIDE-2.5.5-bundle-linux-x86_64/share/minizinc/std/stdlib/stdlib_math.mzn:412:
  in if-then-else expression
  /home/tias/local/src/MiniZincIDE-2.5.5-bundle-linux-x86_64/share/minizinc/std/stdlib/stdlib_math.mzn:416:
  in let expression
  in variable declaration for 'r'
  free variable in non-positive context
File fragment:
5: var bool: p;
6: constraint (((n_neg) ^ 2) >= 1) == (p);
7: solve satisfy;
```

Please @Wout4  make sure the error displays as it should.
Then either fix it or disable those tests (potentially the latter... it is an esoteric expression with the mod inequality)

**Comment by Wout4** [comment]
Only some tests using cumulative are failing for me, can you post the model that gives the error?
