### ISSUE TITLE
refactor to_cnf transform, flatten outside and more robust to globals

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#206]
I noticed `to_cnf()` transformation calls flatten. This is from the old days. Today we chain transformations in the solver interface, so `to_cnf()` should document that it assumes that the input is flat, and just work on that.

Some of the checks before the flatten might go, or some might have to stay.

Also the actual `flat2cnf()` looks a lot like `reify_rewrite()`... although it can assume that its input is CNF; it basically is left to translate == into ->, <- and -> into ~a or b. Though I think it is going to far in that, it perhaps should check that it gets a list of clauses at some point. E.g. that is why I think `BV -> Xor(boolvar(3))` might crash it with a 'Xor is not a variable'...

**Comment by Wout4** [comment]
I think issue #190 can also be resolved by adding a case for Boolexpr == Intvar 
Seems better to not work on that in parallel so either I wait for this refactoring, or @sourdough-bread can also look into that.

I already worked on #190 for ortools and gurobi, just not yet for pysat
