### ISSUE TITLE
mus: converted nested lists to conjunction

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#212]
CPMpy allows lists as (top-level) constraints, and automatically interprets them as conjunctions.

E.g.:
```
bv = boolvar(3)
m = Model()
m += ~all(bv)
m += [v for v in bv]
print(m.solve())
```

is a valid model, that is UNSAT

Our mus tool does not handle that, because bv -> [] is not allowed, it should be bv -> all([...])
```
from cpmpy.tools import mus
mus(m.constraints)
```

I don't think we should complicate our language by allowing lists as conjunctions everywhere (incl in implications). Instead, I think we should have a new simple transformation that transforms any top-level list of an expression into an `all()` constraint.
That way, the mus-tool can first call that transformation on all top-level elements of the list, and then continue as it is now

**Comment by IgnaceBleukx** [comment]
I'm not sure this is actually what a user would expect to happen... For me, posting a set of constraints as list comprehension is just a way to reduce the number of lines in my code... For example this sudoku model:

```python3
model += [AllDifferent(row) for row in cells]
model += [AllDifferent(col) for col in cells.T] 
...
```
Does not mean I want a MUS containing ALL row/column constraints.

I think we actually have 2 options to fix this:
- In `Model.py` only keep a flat list of constraints
- In the mus-tool, we convert the given list of constraints to a flat list before starting the algorithm.

**Comment by tias** [comment]
It should become a new transformation that all solvers will want to use, as they don't have to check for lists then anymore. It can be an argument to this transformation whether to `keep_and=True` keep top-level 'ands' or merge them into the list as well. 

I'm owkay with merging in sublists as individual constraints, a user can put an and() around it if wanted together.
