### ISSUE TITLE
z3: 1-var error

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#231]
```
Model(1-boolvar() > 0).solve("z3")
```

fails with             
```
            # '-'/1
            elif cpm_con.name == "-":
>               return -self._z3_expr(cpm_con.args[0])
E               TypeError: bad operand type for unary -: 'BoolRef'
```

@IgnaceBleukx is there an alternative way, or should we translate it into wsum?

`Model(2*bv[0]-3*bv[1]+4*bv[2] > 0).solve("z3")` does work, `Model(bv[0]-bv[1]+bv[2] > 0).solve("z3")` does not.

**Comment by IgnaceBleukx** [comment]
Well, we translate `x - y` to `x + (-y)` at construction time ([see here](https://github.com/CPMpy/cpmpy/blob/35a70d9f9bbca12ceebbf07170c8f9e32b6a87f7/cpmpy/expressions/core.py#L272)).
So I think what we actually should do is translate `x - y` to a wsum from the start or leave it as a subtraction... But now we translate to some weird intermediate form.

Which of the solutions to chose will be a tradeoff between use-friendlyness and solver-friendlyness... I think it's best to keep it as a subtraction as it makes more sense for the user when he prints the constraints from the model. I would be fine if our Flat Normal Form does not contain subtractions in the output as any solver will convert a subtraction to a wsum internally anyway.

For the z3 specific case, `BoolRef - BoolRef` is not supported either, but for this we can use Wout's simple trick to convert it to ints using z3's `if-then-else` statements.
