### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by federicotoffano** [CPMpy/cpmpy#247]
Hi, how can I set a seed for CPM_ortools?

**Comment by tias** [comment]
Hi Frederico,

We explain a bit how to set solver-specific parameters in the 'Solver Parameter' parts of our docs:
https://cpmpy.readthedocs.io/en/latest/solver_parameters.html

For your case, I can see in the docs of the OrTools parameters, that there is a 'random_seed' parameter:
https://github.com/google/or-tools/blob/stable/ortools/sat/sat_parameters.proto

So a working example would be:
```
s = SolverLookup.get("ortools")  # same as calling CPM_ortools() constructor
iv = intvar(1,9, shape=5)
s += alldifferent(iv)
s.solve(random_seed=42)  # this line
iv.value()
```

Changing the seed for this toy example does not seem to change the solution values though.

I hope this answers your question, if not please do reopen the issue.

**Comment by federicotoffano** [comment]
Hi Tias,

Thanks for your quick reply. I did some tests and it looks like it doesn't work, i.e., I get different solutions solving the same problem. You can check yourself by running this:

```
from cpmpy import *
from cpmpy.solvers import *

rep = 10**4
prev_i = []
prev_b = []
for i in range(rep):
    s = SolverLookup.get("ortools")  # same as calling CPM_ortools() constructor
    s = CPM_ortools()
    iv = intvar(1, 9, shape=5)
    bv = boolvar(shape=5)
    s += [iv[j] % 2 == 0 for j in range(5)] == bv # element-wise comparison, bool var is True if int var is even
    s.solve(random_seed=43, log_search_progress=False)
    res_b = list(bv.value().flatten())
    res_i = list(iv.value().flatten())
    if i > 0:
        if res_b != prev_b:
            print(f"Different results at iteration {i}")
            print('\ncurrent:')
            print(res_i)
            print(res_b)
            print('\nprevious:')
            print(prev_i)
            print(prev_b)
            break
    prev_i = res_i
    prev_b = res_b


```
