### ISSUE TITLE
Cannot `deepcopy` model with nested list of constraints

### ISSUE THREAD

**Issue by HelgeS** [CPMpy/cpmpy#248]
Calling `deepcopy` on a model where a list of constraints has been added, leads to the following error:
```
Traceback (most recent call last):
  File ".../sudoko_example.py", line 42, in <module>
    model.deepcopy()
  File "lib/python3.10/site-packages/cpmpy/model.py", line 265, in deepcopy
    copied_cons = [cpm_cons.deepcopy(memodict) for cpm_cons in self.constraints]
  File "lib/python3.10/site-packages/cpmpy/model.py", line 265, in <listcomp>
    copied_cons = [cpm_cons.deepcopy(memodict) for cpm_cons in self.constraints]
AttributeError: 'list' object has no attribute 'deepcopy'
```

This can be reproduced with [the sudoku example](https://github.com/CPMpy/cpmpy/blob/master/examples/sudoku.py) by adding a `model.deepcopy()` after all constraints have been posted, or by the test at the bottom.

A solution could be to flatten the list of constraints when they are added to the model, but I'm not sure if this might cause other issues.

Modified test to have a nested list of constraints:
```
    def test_deepcopy(self):
        x,y,z = [cp.boolvar(name=n) for n in "xyz"]

        cons1 = x > y
        cons2 = x + y == 1
        cons3 = z > y
        m = cp.Model([cons1, cons2], [cons3])

        memodict = dict()
        m_dcopy = m.deepcopy(memodict)
        print(memodict)
        m_dcopy.solve()

        self.assertIsNone(cons1.value())
        self.assertIsNone(cons2.value())
        self.assertIsNone(cons3.value())

        m.solve()

        m2 = m.deepcopy()

        self.assertTrue(m2.constraints[0].value())
        self.assertTrue(m2.constraints[1].value())
        self.assertTrue(m2.constraints[2].value())
```

CPMpy version: 0.9.12
Python version: 3.10.9

**Comment by IgnaceBleukx** [comment]
Hi Helge, 
Thank you for reporting the bug (and even a testcase to discover it!).
It seems we should have implemented the `__deepcopy__()` function for our Expression objects. One can then simply call `copy.deepcopy(cpm_expr)` to deepcopy the expression (or model for that matter).

I'll fix this as soon as possible!

**Comment by tias** [comment]
Hi Helge,

Turns out that we needlessly implemented our own deepcopy. The default copy.deepcopy(), which also works on lists, works just fine : ) So we use that now, and encourage you to use it too : )

Thanks for reporting!
Tias
