### ISSUE TITLE
Allow finding intermediate solutions with Minizinc

### ISSUE THREAD

**Issue by timvandam** [CPMpy/cpmpy#251]
I am trying to find all intermediate solutions for an optimization problem. `CPM_minizinc` does not allow this, as `solve()` will only return the last solution, and `solveAll()` does not work for optimization problems. I did not encounter this problem for the `CPM_ortools` model, where I can provide a callback to `solve()` to store all intermediate solutions myself

**Comment by timvandam** [comment]
For some additional context, I pass `intermediate_solutions=True` to the `solve()` function to get multiple solutions. I am then met with the `Warning: multiple solutions found, only returning last one` log

**Comment by timvandam** [comment]
The easiest solution would be to simply have an argument change this behavior of `solve()`. I am willing to make a PR for this if this sounds good. Let me know

**Comment by timvandam** [comment]
For those looking for a workaround, I extended the `CPM_minizinc` class to store objective values and timestamps the following way:
```py
class MinizincSolver(CPM_minizinc):
    """
    Wrapper around CPM_minizinc that allows capturing all (intermediate) solutions,
    because CPM_minizinc abandons all but the last solution
    """

    objective_values: List[int]
    objective_values_timestamps: List[float]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.objective_values = []
        self.objective_values_timestamps = []

    def _post_solve(self, mzn_result):
        solutions = mzn_result.solution if is_any_list(mzn_result.solution) else [mzn_result.solution]
        for sol in mzn_result.solution:
            self.objective_values.append(sol.objective)
            self.objective_values_timestamps.append(time.time())
        return super()._post_solve(mzn_result)
```
I then call `solver.solve(intermediate_solutions=True)`, and use `solver.objective_values` and `solver.objective_value_timestamps` to access the information I need

**Comment by tias** [comment]
Hi Tim,

I think that is a very elegant solution.

To have something to main CPMpy would indeed be best with a callback, but if the above solution suits you well then I think we can leave it at that?

**Comment by timvandam** [comment]
> Hi Tim,
> 
> I think that is a very elegant solution.
> 
> To have something to main CPMpy would indeed be best with a callback, but if the above solution suits you well then I think we can leave it at that?

Yes, this works for me. We can leave it at that, but it may be nice for future users. However, I am not sure how common this requirement is
