### ISSUE TITLE
Global cardinality constraint is not general

### ISSUE THREAD

**Issue by JoD** [CPMpy/cpmpy#256]
The global cardinality constraint described in http://sofdem.github.io/gccat/gccat/Cglobal_cardinality.html is more general than the one we have (https://github.com/CPMpy/cpmpy/blob/master/cpmpy/expressions/globalconstraints.py#L551).

Do we want to address this?

**Comment by Dimosts** [comment]
You mean because in our case the user has to define the exact amount of times all values appear, and cannot define it only for a subset of them, right?

**Comment by JoD** [comment]
Yes, exactly.

**Comment by Dimosts** [comment]
I will prepare and alternative version for the more general case and I will open a pull request. Then we can see if we prefer that or the current one.
