### ISSUE TITLE
Table constraint on right hand side of implication crashes linearize_constraint

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#260]
bug found with fuzztesting

iv = intvar(-8,8, shape=3)
bv = boolvar()

cons = [bv.implies(Table(iv,[0,5,4]))]
linearize_constraint(cons)

**Comment by IgnaceBleukx** [comment]
Same issue as #259, unsupported global constraints should be decomposed in `decompose_global`.
If `table` is supported, the constraint falls through the transformation on the current master.
