### ISSUE TITLE
negated_normal crashes when input contains a boolexpr compared with an numexpr.

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#261]
Bug found with fuzztesting, running on flatten_constraint

example: iv = intvar(-8,8, shape=3)

cons = [(iv[0] == iv[1]) == (iv[2] + 3)]
negated_normal(cons[0])

example of how flatten leads to this bug:

cons = [(iv[0] == iv[2]).implies((iv[0] == iv[1]) == (iv[2] + 3)) == 0]
flatten_constraint(cons)

**Comment by JoD** [comment]
runnable code:

```
from cpmpy import *

import numpy

iv = intvar(-8,8, shape=3)

cons = [(iv[0] == iv[1]) == (iv[2] + 3)]
transformations.flatten_model.negated_normal(cons[0])

# example of how flatten leads to this bug:

cons = [(iv[0] == iv[2]).implies((iv[0] == iv[1]) == (iv[2] + 3)) == 0]
transformations.flatten_model.flatten_constraint(cons)
```

**Comment by Wout4** [comment]
This is another argument for a is_numexpr helper function, the is_num check fails here because it is a numerical expression not a variable or number
