### ISSUE TITLE
is_arithmetic function on expressions

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#263]
We already have a is_bool() on expressions, and the more general is_boolexpr() that works on any input.

I think it would be useful to also have an is_arithmetic and corresponding is_arithmeticexpr() because right now we have to use not is_bool, but this is not always correct.

For example: Element global constraint should return False for both since we can not always deduce if it will return bool or int.
list or ndvararray is also not bool and not arithmetic.

**Comment by JoD** [comment]
Having an unknown state for int or bool will make things more complicated: it will be a special case that has to be dragged through many operations, and there are quite some already. 

Proposal: make Element an int. A user can always convert 0 to false and 1 to true by nesting the element expression with '... == 1'.

For the same reason: we should eliminate non-total expressions. For division, we do this by not allowing divisors with a domain containing '0'. We could do the same with Element. If a user really wants the functionality where an index can be out of bounds, the user can add a useless indices to the Element constraint that take the full range of the index.

As for the list, these probably should not be expressions. They are attributes of certain expressions (e.g., of `alldiff` or arbitrary length sums/conjunctions/disjunctions) but not expressions in their own right.

**Comment by JoD** [comment]
What would the difference between `is_num` and `is_arithmetic` be?

**Comment by Wout4** [comment]
is_num checks if its a numerical value (including bools):
```
def is_num(arg):
    """ is it an int or float? (incl numpy variants)
    """
    return isinstance(arg, (bool, np.bool_, int, np.integer, float, np.floating))
```

is_arithmetic should exclude the boolean case.
we should also have a is_numexpr/is_arithmeticexpr helper function that works on expressions
However if we eliminate the unknown cases this won't be needed as we can just negate is_bool
