### ISSUE TITLE
Is it possible to extend the packing_rectangles.ipynb to support multiple bins

### ISSUE THREAD

**Issue by mostpalonen** [CPMpy/cpmpy#264]
Is it possible to extend packing_rectangles.ipynb example in a such way where the items would be packed into multiple bins. Or how should I go about implementing the support for multiple bins.

Those bins might even have varying size and the goal is to select those bins, which minimize the used bin area.

**Comment by tias** [comment]
Are these also 2D bins? if only 1D, then you have a typical bin packing problem, see for example this model from Hakan Kjellerstrand:

http://www.hakank.org/cpmpy/bin_packing.py
http://www.hakank.org/cpmpy/bin_packing_laurent.py

The second one might be more readable. This could be extended to the 2D case too I expect. It might not be very scalable, but there are tricks for that too.

Does this help?

**Comment by mostpalonen** [comment]
This helps a bit. I've come to the conclusion that my problem is more complex than I realized, so I'm still not sure how I will actually solve it.

Shortly, I have n number of circle reel objects that need to be packed onto pallets. Both the reels and pallets can have varying sizes and the reels need to be packed so that the combined area of the pallets is minimal. But the number of pallets required, the size of those pallets and the circular objects make this problem a very complex combination.
