### ISSUE TITLE
Python built-in functions are now returning boolval instead of bool 

### ISSUE THREAD

**Issue by Dimosts** [CPMpy/cpmpy#304]
After the Boolval instead of Bool PR was merged, some python built-in functions, like any or all, return now boolval objects instead of bool!

In projects that use from cpmpy import *, which can use any and all both for creating constraints and also out of cpmpy, this leads to many errors. That is because wherever any or all is used in a condition, the output now is wrong, as it is not a bool anymore.

I strongly believe that we should not change the returning type of built-in functions, at least when they are not used for creating constraints. We could check the iterable given, and if it contains at least one expression make a constraint (even if it is just a boolvar(True) or boolvar(False) constraints), otherwise return bool.

**Comment by Dimosts** [comment]
In order to be able to run experiments for my Constraint Acquisition project, I had to revert the changes in 'any' and 'all' builtin functions and create a seperate branch for now. If we decide to continue with the new 'any' and 'all', returning a different type than the original built-in functions, then I will have to just replace 'from cpmpy import *'  with 'import cpmpy as cp' and then change all the parts I use cpmpy. But I do think that this is not the best solution (not for me, but in general for everyone using cpmpy).

**Comment by tias** [comment]
No, we had commits that fixed that in the branch, so it was never meant to be merged like this; but it seems I forgot to push them and merged the branch without those updates.

We are now doing an emergency release (0.9.14) to correct this.
