### ISSUE TITLE
Adding Choco

### ISSUE THREAD

**Issue by Dimosts** [CPMpy/cpmpy#320]
Could it be an option to add also Choco?

It has a python API (https://pypi.org/project/pychoco/), and as we discussed with Helene, it could be useful in some cases.

**Comment by tias** [comment]
Yes, any solver can become a Tier3 solver (e.g. live in a pull request). Perhaps wait a few more days until #312 is merged, which makes making a new solver interface slightly more explicit/convenient.
You might underestimate how well you need to know there API to write this ; ) but in a pull request it can be done piece by piece
