### ISSUE TITLE
Flatten in utils.py

### ISSUE THREAD

**Issue by 363734** [CPMpy/cpmpy#332]
There is a potential issue with the _flatten/flatlist in utils.py.
It flattens any Iterable.
It is used for example in the __init__ of Operator to flatten the arguments.
If we would to have sets at some point as arguments of an operation (I'm thinking about the case of an 'in set of value' constraint to help define sparse domains), the set would be flattened too.

I think it should be modify to flatten only list structure and not any iterables

**Comment by Dimosts** [comment]
As a side note, for the 'in set of value' constraint, check PR #302. It does not use the operation constructor.

**Comment by Wout4** [comment]
I think it does what it is supposed to do, flatten any iterable. We might have to take care how to use it in the future, but this ties in with refactoring our operators as a whole, https://github.com/CPMpy/cpmpy/issues/334 would remove the case you are talking about
