### ISSUE TITLE
Move flatten operations to normalize/simplify transformation

### ISSUE THREAD

**Issue by JoD** [CPMpy/cpmpy#345]
> we should take the optimisations of nested 'and' and implications of ands etc and move them to the `normalize` transformation (perhaps specifically the `simplify_boolean` operation). That will significantly simplify the flatten code. 
> that will be most powerful after push down negation and decompose is preceding this transfo; so we can do those first

https://github.com/CPMpy/cpmpy/pull/291/files#r1203689588

**Comment by Dimosts** [comment]
I can take that. However, currently simplify boolean is only used to removes boolean constant from all CPMpy expressions. If we move these optimizations to simplify_booleans then the purpose of the function changes. I still think though it should be done, I will create a PR for this.
