### ISSUE TITLE
Extend solver interface

### ISSUE THREAD

**Issue by JoD** [CPMpy/cpmpy#348]
- `solveAll()` could use an argument where the user can pass those variables that need to differ in each solution, e.g., to only search for models that differ on the user variables.
- Add a `propagate()` method that finds the intersection of all solutions (again, on some given set of variables). Exact can then specialize this method to get a stateful propagate() routine.

**Comment by tias** [comment]
solvers can have more functions, or with additional arguments, then the generic SolverInterface. So I'm happy for you to add this to Exact directly.

I don't think we'll want to cover this in all solvers...
