### ISSUE TITLE
trying the example with graph coloring - objective_value returns 1 (rather than the objective)

### ISSUE THREAD

**Issue by zbenmo** [CPMpy/cpmpy#352]
Two issues, maybe related.

1. trying the example with graph coloring - objective_value returns 1 (rather than the objective).

(as the title).

2. Note the objective in the output below. Is this what we wanted to have?

--

```
def solve_cp(edges, node_count):
        
    model = cpmpy.Model()

    max_colors = node_count
    
    # dict of node-names to intvar
    nodecolor = {
        node: cpmpy.intvar(1, max_colors + 1, name=str(node))

        for node in range(node_count)
    }
    
    # constrain adges to have differently colored nodes
    model += [nodecolor[node1] != nodecolor[node2] for node1, node2 in edges]
    
    # minimize number of colors
    model.minimize(max(nodecolor.values()))

    assert model.solve(time_limit=5)

    return model.objective_value(), [nodecolor[node].value() for node in range(node_count)]

```

Below is my model. Note the objective. Is this what we wanted?

Constraints:
    [(0) != (5), (0) != (15), (0) != (32), (0) != (44), (0) != (47), (1) != (4), (1) != (22), (1) != (47), (2) != (5), (2) != (7), (2) != (14), (2) != (22), (2) != (30), (2) != (33), (2) != (42), (3) != (7), (3) != (11), (3) != (12), (3) != (25), (3) != (47), (3) != (49), (4) != (13), (4) != (24), (4) != (45), (5) != (14), (5) != (41), (5) != (44), (6) != (8), (6) != (33), (6) != (49), (7) != (8), (7) != (18), (7) != (30), (7) != (41), (7) != (43), (7) != (47), (8) != (10), (8) != (26), (8) != (32), (8) != (36), (8) != (39), (8) != (47), (9) != (24), (9) != (48), (10) != (18), (10) != (24), (10) != (32), (10) != (40), (10) != (41), (10) != (47), (11) != (13), (11) != (19), (11) != (27), (11) != (36), (11) != (48), (11) != (49), (12) != (23), (12) != (24), (12) != (41), (13) != (33), (14) != (23), (14) != (26), (14) != (45), (15) != (21), (15) != (25), (15) != (29), (15) != (48), (16) != (18), (16) != (19), (16) != (24), (16) != (27), (16) != (30), (16) != (39), (16) != (46), (17) != (19), (17) != (20), (17) != (23), (17) != (44), (17) != (49), (18) != (22), (18) != (30), (18) != (37), (19) != (26), (19) != (36), (19) != (38), (19) != (41), (19) != (46), (20) != (30), (20) != (40), (21) != (35), (21) != (40), (21) != (48), (22) != (34), (22) != (35), (22) != (37), (23) != (39), (25) != (37), (25) != (38), (25) != (46), (25) != (49), (26) != (27), (26) != (43), (26) != (47), (27) != (42), (27) != (43), (27) != (46), (27) != (47), (27) != (49), (28) != (43), (28) != (44), (29) != (40), (29) != (45), (30) != (38), (30) != (40), (30) != (47), (31) != (32), (31) != (35), (32) != (36), (32) != (44), (32) != (48), (33) != (34), (33) != (40), (35) != (39), (37) != (48), (38) != (48), (39) != (46), (40) != (43), (41) != (49), (44) != (45), (44) != (47), (45) != (49), (46) != (47), (47) != (49)]
Objective: minimize 49

-> the output (first line objective and then 0 for 'optimal <- not sure==status, second line the coloring)':

1 0
14 10 8 6 11 15 2 7 5 5 1 5 3 1 3 5 7 2 2 6 1 3 9 1 8 2 4 2 1 1 5 1 13 5 1 2 1 1 1 4 4 2 1 5 12 2 3 11 4 1

**Comment by Dimosts** [comment]
Hello,

this happens because the wrong max() function is used. In the graph colouring example, we have used 

`from cpmpy import *`

so the python built-in max() function is replaced by our cpmpy max() function. However, in your code you have imported cpmpy as cpmpy. So, in order to used cpmpy functions, you need to use cpmpy.function().

In this particular case, cpmpy.max() will do what is required.

**Comment by zbenmo** [comment]
perfect, thanks!
