### ISSUE TITLE
indomain does not work with minizinc

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#366]
example: Model([InDomain(iv,[1,2,3])]).solve("minizinc")

**Comment by Dimosts** [comment]
#370 #365 and this are similar errors, we just don't handle these for Minizinc. We should open a PR dealing with all of them, and other similar cases that can occur.

**Comment by Wout4** [comment]
I see 3 possible solutions
1. Run decompose globals for minizinc
  Easiest to implement
  Big overhead since almost everything is supported? 
  Don't think we can specify that global functions are only supported in a comparison
2. Add cases for all these unsupported globals
  This is kind of what we have been doing
  Harder to maintain
3. Have a supported list similar to decompose in tree, and decompose when creating minizinc text
  Future proof but won't easily work for globals that also have a defining part next to the constraining part and for global functions...

**Comment by Dimosts** [comment]
Decompose globals does take care of global functions that are not in a comparison. So I think this should be the case. For the ones supported (like Alldifferent_except_0) we should just specify how to write it in minizinc like we do for the rest. We could also do that for InDomain, specify directly that it should decompose and avoid the overhead of decompose_globals. But I am in favour of using decompose_globals due to the globalfunctions

**Comment by Wout4** [comment]
Only thing with the current version of decompose_in_tree: there is no way to only support global functions within a comparison.
with count in supported  but not in supported reified this does not get decomposed:  [(count([IV1,IV2,IV3],1)) - 2 == 0] (maybe it should?)
with count not in supported it always gets decomposed, which we also don't really want since we support [(count([IV1,IV2,IV3],1)) == 0]

**Comment by Dimosts** [comment]
oh, we do not flatten that in decompose_in_tree??? That is a problem.

We should flatten [(count([IV1,IV2,IV3],1)) - 2 == 0] to [IV4 - 2 == 0, (count([IV1,IV2,IV3],1) == IV4) ]

**Comment by Wout4** [comment]
well we shouldn't if there is some solver that supports it unflattened, but i guess there isn't?

**Comment by Dimosts** [comment]
There isn't any as far as I know. 

I opened a PR with that, so we can proceed with solving these 3 issues by using decompose_in_tree and adding more cases in minizinc
