### ISSUE TITLE
Minizinc solve call crashes JSON-decoder on specific output

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#386]
Bug found while fuzztesting.

Removing any constraints eliminates the bug. Minizinc does return a solution, but the JSON being decoded has an entry 'BV4': BV4, in stead of an entry 'BV4': true (or any other value).
Not sure what the cause is.

runnable example:
BV8 = boolvar()
BV7 = boolvar()
BV4 = boolvar()
m = Model([(~BV8) == (BV7), (~BV8) == (BV7), (~BV8) == (BV7), (~BV8) == (BV7), (~BV8) == (BV7), (~BV8) == (BV7), (~BV8) == (BV7), (~BV8) == (BV7), ((~BV8) == (BV7)) | ((~BV8) == (BV7)), ((~BV8) == (BV7)) == (BV4), BV4])
m.solve("minizinc")

**Comment by tias** [comment]
It looks like you found yourself a MiniZinc bug!

simplifieder:
```
from cpmpy import *
BV8 = boolvar(name="BV8")
BV7 = boolvar(name="BV7")
BV4 = boolvar(name="BV4")
BV9 = boolvar(name="BV9")
m = Model([(BV9) | ((~BV8) == (BV7)),
           ((~BV8) == (BV7)) == (BV4),
           BV4])
m.solve("minizinc")
```

I think MiniZinc is doing CSE on the `(~BV8) == (BV7)` part and then later sees it can simplify BV4 away but looses something along the way...

Best report upstream...

**Comment by Wout4** [comment]
reported minizinc bug here: https://github.com/MiniZinc/libminizinc/issues/716
(it does also occur in minizinc IDE)
