### ISSUE TITLE
cp.intvar makes unbound variables? 

### ISSUE THREAD

**Issue by jpcaveiro** [CPMpy/cpmpy#397]
In the following example there are four variables `0 <= b[i] <= 1`. Why is there only one solution instead of 16?

* Why does `cp.intvar` not make a domain condition in each variable? 

```python
import cpmpy as cp
b = cp.intvar(0, 1, shape=5, name="b")  # five binary variables
m = cp.Model(b[0] == 1)
print("Nr of solutions:", m.solveAll() ) #Why Nr of solutions is only 1 ?
```

* version '0.9.16'

**Comment by IgnaceBleukx** [comment]
Hi João,
Thanks for reaching out.
In CPMpy a variable is not associated with a model up on creation.
So, integer values `b[1]` to `b[4]` are not "known" to the model and indeed not to the solver.
If you print the model, you will get the following:
```python3
print(m)
>>Constraints:
        b[0] == 1
    Objective: None
```

You can force the model to take into account all of the variables you created by putting them in a constraint which will always be True, in your case you could use something like `cp.sum(b) >= 0`.
This way, the variables are known to the solver, but unconstrained.

```python3
import cpmpy as cp
b = cp.intvar(0, 1, shape=5, name="b")  # five binary variables
m = cp.Model(b[0] == 1)
m += cp.sum(b) >= 0
print("Nr of solutions:", m.solveAll() ) # this will result in 16 solutions
```

I hope this cleared things up :)

**Comment by jpcaveiro** [comment]
Thank you.
