### ISSUE TITLE
Solution hinting not working as intended when NDVarArray more than 1 dimension 

### ISSUE THREAD

**Issue by Dimosts** [CPMpy/cpmpy#407]
If we define a variable array with more than 1 dimension, solution hinting is not working

Slightly changing the example we have in the docs for solution hinting (https://cpmpy.readthedocs.io/en/latest/solvers.html) to 2D var array, it is not working anymore.

Reproduce:
from cpmpy import *
x = intvar(0,10, shape=(2,2))
s = SolverLookup.get("ortools")
s += sum(x) <= 10
s.solution_hint(x, [[1,2],[3,4]])
s.solve()
print(x.value())

Error:
TypeError: unhashable type: 'NDVarArray' (line 244 of ortools.py)

However, the error actually comes from lines 522-524, where we call solver_var(), assuming that cpm_var is 1 dimention, using a for to iterate.

**Comment by Wout4** [comment]
looks good to me, but I can't get ortools to actually give me a solution that is using the hints. Is that because the problem is just too easy?

**Comment by Dimosts** [comment]
Probably yes, because it is too easy. Sme happens with the 1-D solution hinting we have in master
