### ISSUE TITLE
Pysat removing literals during cardinality encoding

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#409]
bv = boolvar(shape=3)
Model(sum(bv) < 10).solve('pysat')
print(bv.value())

When any solution is valid pysat returns None, instead of a random solution

**Comment by IgnaceBleukx** [comment]
This has to do with Pysat's built-in cardinality encodings (changed title accordingly).
Like many issues we have when optimizing some expressions, the variables are never seen by the solver as the cardinality encoding will simply return an empty list (equivalent to `True`)
We can either special case this in the Pysat solver interface, or (probably less efficient) call `self.solver_vars(self.user_vars.keys())` before the solve-call to make sure all user variables are known to the underlying solver.

**Comment by IgnaceBleukx** [comment]
This issue is solved by #463, closing.
