### ISSUE TITLE
Creating intvar with a specific domain

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#43]
What is the proper way to restrict the values to a specific domain, for example `[3,5,7,8,10]`.
  
The following works but it would be nice to have this in `intvar` directly.
```pythons
vals = [3,5,7,8,10]
Age = intvar(min(vals),max(vals),shape=n,name="Age")
# Fix the domain
for i in range(n):
    model += (member_of(vals,Age[i]))
```

A suggestion would be something like this:
```python
Age = intvar(vals,name="Age")
```

(This is from my Exodus model http://hakank.org/cpmpy/exodus.py)

**Comment by Wout4** [comment]
we have introduced a new global constraint for this purpose, called InDomain.
You would have to add a constraint InDomain(Age,vals) to your model (so it is still at modelling level, not the actual variable domain that get's reduced)
