### ISSUE TITLE
reifing a boolean expression to an integer crashes ortools and gurobi interface

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#442]
```
d = boolvar()
p = boolvar()
i == intvar(1,8)
Model((p == d) == i).solve('gurobi')
```

It does not matter if d or p are bool or int, but when i is int, this crashes.

Found because add solution morph crashed

**Comment by IgnaceBleukx** [comment]
Hmm, for me this is a case where the user wants to use an integer as Boolean, which we do not support.
The above constraint is semantically equivalent to 
```
(~i | (p == d)) & ((p != d) | i)
```
which we would never allow to be written.
I think this caught in the type checks at the construction time of the `==` expression.

If the user would really like to express the consrtaint you wrote, it would be `((p == d) == (i == 1))` which does work :)

**Comment by Wout4** [comment]
well it depends how you look at it, it's valid to use `p == d` as an integer..
If we don't want to allow it we have to catch it (in flatten?) and throw an error anyway, so might as well fix it imo.
