### ISSUE TITLE
Feature request: matrix_element

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#45]
CPMpy supports `element` constraint for single arrays, but it would be great with a matrix variant, `matrix_element`, either as `z == matrix_element[x,i,j]` or - even better - `z == x[i,j]`. Note that `x`, `i`, `j`, and `z` might be `intvar` (or perhaps `boolvar`).

The Hidato puzzle (see http://hakank.org/cpmpy/hidato.py for a complete model) is an example when `matrix_element` would simplify the modelling. Here is the way I model it now, using a flattened version of the matrix (`x_flat`) and then use these `element` constraint:
```python
    # ...
    # Find this k and find k+1
    for k in range(1,r*c):
        i = intvar(0,r)
        j = intvar(0,c)
        a = intvar(-1,1)
        b = intvar(-1,1)
        model +=[
            k == Element(x_flat,i*c+j),
            k + 1 == Element(x_flat,(i+a)*c+j+b)
            ]
```

Instead, it would be convenient to be able to write it like this:
```
    # ....
    # Find this k and find k+1
    for k in range(1,r*c):
        i = intvar(0,r)
        j = intvar(0,c)
        a = intvar(-1,1)
        b = intvar(-1,1)
        model +=[
            k == x[i,j], # or k = matrix_element(x,i,j) 
            k + 1 == x[i+a,j+b] # or k = matrix_element(x,i+a,j+b)
          ]
```

The program http://hakank.org/cpmpy/hidato.py has a couple of test cases.

Some other examples where `matrix_element` could be used:
- http://hakank.org/cpmpy/calvin_puzzle.py
- http://hakank.org/cpmpy/knights_path.py
- http://hakank.org/cpmpy/rogo2.py
 

Note: One can model Hidato problem using the `table` constraint instead, see http://hakank.org/cpmpy/hidato_table.py , but `matrix_element` would be great to have in the tool box.

**Comment by Wout4** [comment]
We now support multi-dimensional element constraints, so (the first option of) your example should work now.
