### ISSUE TITLE
Multiple AllDifferent constraints results in wrong solution

### ISSUE THREAD

**Issue by mekhall** [CPMpy/cpmpy#450]
I have a situation where I gradually expand my model with variables, and as I go along I need to test solve before adding new variables.

All my intvars should always be different.

I have a situation where I get a solution where several of my intvars get the same value even though they are part of a AllDifferent.

Here is my model:
Constraints:
    ((A) // 5) != ((C) // 5)
    ((A) mod 5) != ((C) mod 5)
    ((A) // 5) == ((V) // 5)
    ((C) // 5) == ((Y) // 5)
    ((A) mod 5) == ((Y) mod 5)
    ((C) mod 5) == ((V) mod 5)
    alldifferent(V,Y,A,C)
    ((T) // 5) != ((U) // 5)
    ((T) mod 5) != ((U) mod 5)
    ((T) // 5) == ((R) // 5)
    ((U) // 5) == ((S) // 5)
    ((T) mod 5) == ((S) mod 5)
    ((U) mod 5) == ((R) mod 5)
    alldifferent(V,Y,A,C,R,S,T,U)
    ((A) // 5) != ((L) // 5)
    ((A) mod 5) != ((L) mod 5)
    ((A) // 5) == ((T) // 5)
    ((L) // 5) == ((K) // 5)
    ((A) mod 5) == ((K) mod 5)
    ((L) mod 5) == ((T) mod 5)
    alldifferent(V,Y,A,C,R,S,T,U,K,L)
    ((I) // 5) != ((T) // 5)
    ((I) mod 5) != ((T) mod 5)
    ((I) // 5) == ((S) // 5)
    ((T) // 5) == ((V) // 5)
    ((I) mod 5) == ((V) mod 5)
    ((T) mod 5) == ((S) mod 5)
    alldifferent(V,Y,A,C,R,S,T,U,K,L,I)
    ((I) // 5) != ((E) // 5)
    ((I) mod 5) != ((E) mod 5)
    ((I) // 5) == ((S) // 5)
    ((E) // 5) == ((D) // 5)
    ((I) mod 5) == ((D) mod 5)
    ((E) mod 5) == ((S) mod 5)
    alldifferent(V,Y,A,C,R,S,T,U,K,L,I,D,E)
    ((S) // 5) != ((O) // 5)
    ((S) mod 5) != ((O) mod 5)
    ((S) // 5) == ((Q) // 5)
    ((O) // 5) == ((L) // 5)
    ((S) mod 5) == ((L) mod 5)
    ((O) mod 5) == ((Q) mod 5)
    alldifferent(V,Y,A,C,R,S,T,U,K,L,I,D,E,Q,O)
Objective: None

And here are the values that the solution finds:

V : 14
Y : 24
A : 9
C : 19
R : 14
S : 24
T : 9
U : 19
K : 23
L : 22
I : 15
D : 24
E : 23
Q : 6
O : 11

As you can see V and R get the same value, and they are part of an AllDifferent constraint.

What am I doing wrong here?

**Comment by mekhall** [comment]
I'm trying to attach my code here.

**Comment by mekhall** [comment]
Attaching did not work, so here it comes:
`
import cpmpy as cp
import copy

def addSameCol(m, a, b):
    m += (a % 5) == (b % 5)

def addSameRow(m, a, b):
    m += (a // 5) == (b // 5)

def addRightOf(m, a, b):
    addSameRow(m, a, b)
    m += (a % 5) == (((b % 5) + 1) % 5)

def addUnder(m, a, b):
    addSameCol(m, a, b)
    m += (a // 5) == (((b // 5) + 1) % 5)

def addDifferentRow(m, a, b):
    m += (a // 5) != (b // 5)
    
def addDifferentCol(m, a, b):
    m += (a % 5) != (b % 5)


def addDiagonalRule(model, ci1, ci2, cl1, cl2):
    # cl1 and cl2 are not on the same row nor column
    addDifferentRow(model, ls[letters[cl1]], ls[letters[cl2]])
    addDifferentCol(model, ls[letters[cl1]], ls[letters[cl2]])
    # cl1 and ci1 are on the same row
    addSameRow(model, ls[letters[cl1]], ls[letters[ci1]])
    # cl2 and ci2 are on the same row
    addSameRow(model, ls[letters[cl2]], ls[letters[ci2]])
    # cl1 and ci2 are on the same column
    addSameCol(model, ls[letters[cl1]], ls[letters[ci2]])
    # cl2 and ci1 are on the same column
    addSameCol(model, ls[letters[cl2]], ls[letters[ci1]])
    
def addRowRule(model, ci1, ci2, cl1, cl2):
    # cl1 and cl2 are on the same row
    addSameRow(model, ls[letters[cl1]], ls[letters[cl2]])
    # cr1 is to the right of cl1
    addRightOf(model, ls[letters[ci1]], ls[letters[cl1]])
    # cr2 is to the right of cl2
    addRightOf(model, ls[letters[ci2]], ls[letters[cl2]])

def addColumnRule(model, ci1, ci2, cl1, cl2):
    # cl1 and cl2 are on the same column
    addSameCol(model, ls[letters[cl1]], ls[letters[cl2]])
    # cr1 is under cl1
    addUnder(model, ls[letters[ci1]], ls[letters[cl1]])
    # cr2 is under cl2
    addUnder(model, ls[letters[ci2]], ls[letters[cl2]])



letters = {}
def createLetter(l, l_ls):
    if l in letters:
        return letters[l]
    index = len(l_ls)
    letters[l] = index
    l_ls.append(cp.intvar(0, 24, name=l))
    return index

# ls is a collection of intvars
ls = []

def reset():
    letters = {}
    ls = []

def has_solution(check, answer):
    # Create a single model to start with:
    models = []
    models.append(cp.Model())

    # Add a letter pair at a time.
    # Each letter pair should generate three new models per existing model, one for each rule
    # If a model becomes impossible (= 0 solutions) it is not kept.

    for index in range(len(check) // 2):
        check_letter_1 = check[index * 2]
        answer_letter_1 = answer[index * 2]
        check_letter_2 = check[index * 2 + 1]
        answer_letter_2 = answer[index * 2 + 1]
        print("Processing", answer_letter_1, "->", check_letter_1, "and", answer_letter_2, "->", check_letter_2)
        createLetter(check_letter_1, ls)
        createLetter(check_letter_2, ls)
        createLetter(answer_letter_1, ls)
        createLetter(answer_letter_2, ls)

        # Save good new models in a new array
        new_models = []

        for model in models:        
            new_1 = copy.deepcopy(model)
            addDiagonalRule(new_1, check_letter_1, check_letter_2, answer_letter_1, answer_letter_2)
            new_1 += cp.AllDifferent(ls)
            if new_1.solve():
                new_models.append(new_1)


            new_2 = copy.deepcopy(model)
            addRowRule(new_2, check_letter_1, check_letter_2, answer_letter_1, answer_letter_2)
            new_2 += cp.AllDifferent(ls)
            if new_2.solve():
                new_models.append(new_2) 


            new_3 = copy.deepcopy(model)
            addColumnRule(new_3, check_letter_1, check_letter_2, answer_letter_1, answer_letter_2)
            new_3 += cp.AllDifferent(ls)
            if new_3.solve():
                new_models.append(new_3)

        print("Number of new models:", len(new_models))
        print("")
        models = new_models
        if len(new_models) == 0:
            return False

    if len(models) > 0:
        print("One solution:")
        print(letters.keys())
        model = new_models[0]
        print(model)
        res = model.solveAll(display=solutionCallback, solution_limit=1)
#        res = model.solveAll(display=ls, solution_limit=1)
        return True
    return False

solution = {}
def solutionCallback():
    global solution
    solution = {}
    for letter in letters:
        var = ls[letters[letter]].value()
        solution[var] = letter
        print(letter, ":", var)

check    = "VYRSTKSVSDQL"
answer   = "ACTUALITIESO"
if has_solution(check, answer):
    print("Has solution")
else:
    print("Has no solution")

`

**Comment by mekhall** [comment]
[issue.txt](https://github.com/CPMpy/cpmpy/files/14213213/issue.txt)

**Comment by mekhall** [comment]
I had to rename my file to .txt for it to be attchable, but there it is.

**Comment by Dimosts** [comment]
That required some debugging.

So, as you are making new models by deep copying, the variables of the new alldifferents are not the same ones as the variables of the old alldifferents, and the variables that you have originally created and printing. 

Why don't you make a copy by using the copy() method of our Model class?

It creates new models (so any change to that model does not happen to the copied one and vise versa), but the variables and constraints are the original ones.

**Comment by mekhall** [comment]
I am very greatful for your help debugging this. Thank you for taking your time!

The reason I did not use copy() on the Model class is that it is documented like this:

"
Makes a shallow copy of the model. Constraints and variables are shared among the original and copied model.
"

So it sounds like it would actually share constraints. My copies need to be able to have different constraints.
But as you pointed out, it means that I need to handle the fact that the variables in the copies are not the same as the ones in the AllDifferents. I need to think about this.

I will test the Model.copy() as well just to be sure.

**Comment by mekhall** [comment]
Well, this is interesting: using the model.copy() actually seems to work just fine for my use case!

I thought that it would mean that if I add a certain constraint to a model, the same constraints would be added to all copies made from that model.

**Comment by Dimosts** [comment]
Indeed, we need to specify it in the documentation.

We mean that the variable and constraint objects are shared, but the actual model with its list of constraints are different, so the copied model can have additional constraints.

**Comment by mekhall** [comment]
Oh, that is exactly what I wanted all along then! That's great! :)

Again: thanks for taking your time helping beginners like me.

**Comment by mekhall** [comment]
The documentation is now so clearly written that even I understand it. ;)
Thank you!
