### ISSUE TITLE
wrap_brackets maximum recursion depth

### ISSUE THREAD

**Issue by ThomSerg** [CPMpy/cpmpy#467]
wrap_brackets() inside the \_\_repr\_\_() of Operator can trigger a maximum recursion depth error when trying to rewrite a very large array.

example:
```python
import cpmpy as cp
import numpy as np

n = 1000

A = np.random.randint(0, 5, size=n)
B = cp.boolvar(shape=n)

C = A * B # [ int*boolvar, int*boolvar, ... ]

o = 1
for b in C:
    o *= b

print(o) # tries rewriting as (((((((((... (((int*boolvar) * (int*boolvar)) * (int*boolvar))
```

The recursion is \_\_repr\_\_() -> wrap_bracket() -> \_\_str\_\_() -> \_\_repr\_\_() -> ...
This is expected behavior, but for large arrays a RecursionError gets triggered.

**Comment by Wout4** [comment]
Do you actually want to print that, or does the error occur in some other place? Not sure if we need to fix this as it seems useless to print such big constraints anyway

**Comment by ThomSerg** [comment]
I don't need to print it, I just did when encountering another RecursionError between normalized_numexpr() and get_or_make_var() created by flatten_objective() when I have a very big expression for the objective. Just wanted to let you know. No need to fix it.

**Comment by ThomSerg** [comment]
Should I open an issue for that other RecursionError?

**Comment by Wout4** [comment]
I think we can include it in this one :)

**Comment by ThomSerg** [comment]
It's really similar; when the objective is way too big it makes `flatten_objective()` fail with a maximum recursion error (which is kind of vague towards the user). 

Here's minimal code to replicate the issue:
```python
import cpmpy as cp
import numpy as np

n = 1800
k = 70

A = np.random.randint(0, 2, size=(k,n))
B = cp.boolvar(shape=(k,n))
C = A * B
D = [ cp.sum( C[:,i]) for i in range(n) ]

o = 1
for d in D:
    o = o * d
    
model = cp.Model()

model.maximize(o)

model.solve()
```

The recursive calls of `normalized_numexpr()` and `get_or_make_var()` trigger the error.

**Comment by Wout4** [comment]
I would argue the recursion depth error makes enough sense to not catch it, being able to nest almost 1000 levels deep seems acceptable ;)
