### ISSUE TITLE
Error when running pysat as solver: No module named 'pysat.formula'

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#50]
When solving with PySat I got an error (see below) running this model:
```
from cpmpy import *
import cpmpy.solvers
import numpy as np

def pysat_test():
    x = intvar(0,9,shape=8)
    s,e,n,d,m,o,r,y = x
    constraints = [    (s*1000 + e*100 + n*10 + d) 
                     + (m*1000 + o*100 + r*10 + e) 
                    == (10000*m + 1000*o + 100*n + 10*e + y),
                  s > 0,m > 0,
                  AllDifferent(x)
                 ]
    
    model = Model(constraints)
    stats = model.solve(solver="pysat")
    # These two works:
    # stats = model.solve(solver="ortools")
    # stats = model.solve(solver="minizinc")
    print(stats)
    print(x.value())

pysat_test()
```

Here is the error that is thrown:
```
  File "pysat_test.py", line 23, in pysat_test
    stats = model.solve(solver="pysat")
  File "/usr/local/lib/python3.7/site-packages/cpmpy/model.py", line 130, in solve
    s = solver_class(self)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/pysat.py", line 88, in __init__
    from pysat.formula import IDPool
ModuleNotFoundError: No module named 'pysat.formula'

```

Using ortools or minizinc as solver works without any problem.

**Comment by tias** [comment]
You installed the wrong pysat package, it should be 'python-sat'. I'll add an extra check for it.

**Comment by tias** [comment]
I mean that you should install 'python-sat', there seems to be indeed a 'pysat' satelite-related package... but python-sat calls itself pysat all the time as well

**Comment by hakank** [comment]
Ah, that explains it!

After installing `python-sat` I get this error:
```
NotImplementedError: Non-Boolean variables not (yet) supported. Reach out on github if you want to help implement a translation
```

but I guess that is expected.

**Comment by tias** [comment]
Yes, only pure Boolean variables and Boolean constraints : ) Not even cardinality constraints yet, even though PySat has all the transformations in a separate module.

Picat has all the nice int-to-Bool transformations, we might add something step-by-step, but not a high priority
