### ISSUE TITLE
MiniZinc: How to set flags to a specific solver?

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#52]
Some FlatZinc solvers often work best with the `-f` flag (free search), e.g. Chuffed and OR-Tools. But how do I set this flag in a CPMpy model?

**Comment by tias** [comment]
Still have the right page open coincidentally : )

kwargs to `solve()` are passed to the underlying API, in case of MiniZinc:
https://github.com/MiniZinc/minizinc-python/blob/develop/src/minizinc/instance.py

so for you free_search=True and optimisation_level=0..5 are the ones you probably care about. `ss.solve(free_search=True, optimisation_level=0)`

**Comment by hakank** [comment]
Thanks. And thanks for the link.
