### ISSUE TITLE
cpm_array(m.T) returns m in stead of m.T

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#554]
```
iv = intvar(-4,4, shape=(5,5))
print(iv)
print(cpm_array(iv.T))
```

not sure what happens, cpm_array calls the ndvararray constructor, (variables.py 
```
    def __init__(self, shape, **kwargs):
        Expression.__init__(self, "NDVarArray", self)
```
but this calls the expression init, without using the kwargs (the transposed matrix is in the buffer argument i think).

but doing this doesnt fix it because we flatten in the expression init:
```
    def __init__(self, shape, **kwargs):
        Expression.__init__(self, "NDVarArray", kwargs['buffer'])
```
```
            if isinstance(arg_list[i], np.ndarray):
                # must flatten
                arg_list[i] = arg_list[i].reshape(-1)

```

this reshape also gets rid of our transposed form somehow

**Comment by IgnaceBleukx** [comment]
Hmm tricky stuff indeed.
[This part of the numpy docs](https://numpy.org/doc/2.1/user/basics.copies.html#how-to-tell-if-the-array-is-a-view-or-a-copy) explains it quite well.

We are currently taking "buffer" as the content of the array, but it is unchanged when acting on a view (such as `ndarray.T`). So, I think we have to check whether we are acting on a view, and if so: either throw an error to the user, or make a proper copy of the view and use that.

**Comment by Wout4** [comment]
i was a bit confused by how our NDVarArray constructor works, but because it inherits from np.ndarray, i guess first numpy's constructor gets called, initialising the 'self' within our own init.
Apperently there is a flag in ndarrays to indicate if you are row-major (C-style) or column-major (Fortran-style). Transposing a matrix just sets this flag, so the data doesn't have to change.
Adding this flag correctly to the call to NDVarArray then fixes our problem (see pull request)

**Comment by tias** [comment]
So we seem to agree that the PR fixes it.

For the specific example, instead of
```
iv = intvar(-4,4, shape=(5,5))
print(iv)
print(cpm_array(iv.T))
```
one should do 
```
iv = intvar(-4,4, shape=(5,5))
print(iv)
print(cpm_array(iv).T)
```
and get desired behaviour? 

but that is not how the bug appeared I guess

**Comment by Dimosts** [comment]
Yes, the issue is that the call to cpm_array can be hidden in e.g. a global constraint. For example, maybe an np array is given somewhere, and in some cases a cpm_array may need to be created.

The other option I see, is to enforce in all these cases to accept only cpm_arrays, which, though it could complicate things for the users.
