### ISSUE TITLE
Objective in GCS does not have any influence on solution quality

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#559]
There seems something wrong in the interface to GCS.
I'm not sure if its CPMpy or the Python API of GCS itself.

```python
import cpmpy as cp

vars = cp.intvar(0,10, shape=3)
model = cp.Model(cp.AllDifferent(vars), maximize=cp.sum(vars))

solver = cp.SolverLookup.get("gcs", model)
assert solver.solve()
print(vars.value())
```
Shows `[0,1,2]` while clearly the optimal value assigns 10,9 and 8 to the variables.

GCS has a handy function `get_api_calls_str()` function, which returns the following log:
```
auto v0 = p.create_integer_variable(0_i, 10_i);
auto v1 = p.create_integer_variable(0_i, 10_i);
auto v2 = p.create_integer_variable(0_i, 10_i);
p.post(AllDifferent{{v0, v1, v2}});
auto v3 = p.create_integer_variable(0_i, 30_i);
p.post(LinearEquality{WeightedSum{} + 1_i * v0 + 1_i * v1 + 1_i * v2 + -1_i * v3, 0_i});
p.minimise(v3); # oh ow...
solve
get_solution_value
get_solution_value
get_solution_value
get_solution_value
get_solution_value
```

I did a little digging already, and found this func in `gcspy-0.1.3/python/gcspy.cpp` which explains the faulty logging, but it seems only part of the problem as the logic is correct.
Moreover, minimizing the negated objective yields the same issue...

```cpp
auto Python::maximise(const string & var_id) -> void
{
#ifdef WRITE_API_CALLS
    api_calls << "p.minimise(v" << var_id << ");" << endl;
#endif
    p.maximise(get_var(var_id));
}
```

@mmcilree maybe you can help out here : )

**Comment by mmcilree** [comment]
Ah... I think I know what's happening. 

If `all_solutions=false`(as is default) gcspy stops as soon as it finds any solution regardless of whether it's optimising or not. But I guess the expected behaviour of solve when maximising should be to keep going until it finds the optimal solution regardless of whether `all_solutions` is set. This was an oversight on my part.

This should be easy to fix. Does GCS get it right in your example if you do `solve(all_solutions=True)`?

**Comment by IgnaceBleukx** [comment]
Hi Matthew,

In the CPMpy interface we do set the `all_solutions` flag to True when we are optimizing:
https://github.com/CPMpy/cpmpy/blob/cd374de99445a7bdbcbe20525eb1c07b1d8b82db/cpmpy/solvers/gcs.py#L137

When printing the statistics after solve I get this, so the enumeration seems to work fine?
```
{'completed': 1, 'max_depth': 3, 'solutions': 25, 'solve_time': 0, 'contradicting_propagations': 11, 'effectful_propagations': 51, 'propagations': 158, 'n_propagators': 2, 'failures': 11, 'recursions': 47
```

**Comment by IgnaceBleukx** [comment]
Aha, yes that did it! 
I'll open a simple PR to update it, thanks for the quick answers!
