### ISSUE TITLE
Programs in examples/visual_examples requires fonts that are not installed by default (Linux Ubuntu)

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#59]
The new and great visual examples in `examples/visual_examples` uses TrueType fonts:
```
myFont = ImageFont.truetype("arialbd.ttf", 20, )
```

However, this font (arialbd.ttf) is not installed by default on my Linux Ubuntu 18.06 machine. Instead there's an error:
```
OSError: cannot open resource
```

Happily, I had that font installed somewhere else and could just symlink it to the `examples` directory, and could then run the programs. Very nice!

Would it be possible to add `arialbd.ttf` to the cpmpy distribution?

Later note: A tip from https://askubuntu.com/questions/956156/my-ubuntu-does-not-want-to-know-arial was to install the Microsoft Fonts via `sudo apt install ttf-mscorefonts-installer`. That worked without any problem, though I had to accept the EULA etc.

**Comment by tias** [comment]
latest commit tries the default and only falls back on the less appealing one if font is missing, thanks for reporting!
