### ISSUE TITLE
Possible bug in CPM_ortools.solution_hint

### ISSUE THREAD

**Issue by stradivari96** [CPMpy/cpmpy#83]
Calling `ClearHints` inside the loop will only pass the hint for the last variable to or-tools
https://github.com/CPMpy/cpmpy/blob/3bd977013418cd8b94a96f7b739623fb8fdee680/cpmpy/solvers/ortools.py#L156-L158

**Comment by tias** [comment]
Yes! That should be outside the loop... Thanks for reporting, will fix in a minute
