### ISSUE TITLE
Unifying solver interfaces

### ISSUE THREAD

**Issue by IgnaceBleukx** [CPMpy/cpmpy#86]
Implementations of the `SolverInterface` class are not homogeneous.
In several solvers, code is duplicated and difficult to maintain.

We would like to reify the generic interface so it also supports MIP solvers which can be added later.
Issue also includes the creation of a template interface implementation for use by external solver developers.

Current solvers must be reimplemeted in this new interface
Tasks:
- Make template interface
- Reify parent class `SolverInterface`
- Reimplement PySat
- Reimplement OR-tools
- Reimplement MiniZinc

**Comment by tias** [comment]
Fixed in pull request #85, merged and released in 0.9.8
