### ISSUE TITLE
lb/ub computation of expressions

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#96]
This is currenlty done in cpmpy/transformations/flatten.py, function 'get_or_make_var()'

Should we take it out into a separate 'transformation' that only computes the bounds?

Or should we add a function get_lb()/get_ub() to the Expression objects directly?

Undecided, opinions welcome.

**Comment by IgnaceBleukx** [comment]
I think bounds calculation can become a separate transformation.
This would allow other transformations to calculate bounds without having to deal with the side effects of get_or_make_var, such as constraint generation.
Adding them in the core would add a lot of code, although it would allow us to cache the result of get_lb()/get_ub() so future lookups can be more efficient. Of course assuming that uses do not change an expression manually...

As the code is structured around the transformations, my preference goes to implementing a separate transformation for this

**Comment by IgnaceBleukx** [comment]
Related to this is the following bug:
```python
arr = boolvar(shape=3, name="arr")
idx = intvar(lb=0, ub=2, name="idx")

cons  = arr[idx]

get_or_make_var(cons)
>> (IV0, [arr[0],arr[1],arr[2]][idx] == IV0)
```
Instead of creating an integer variable, we should create a new boolean variable.

This messes things up when assigning cons to a new variable and using only_bv_implies. IV0 then occurs as base constraint which is not allowed as it is numeric...
For example:

```python
a = boolvar(name="a")
b = boolvar(name="b")

cons = a == (arr[idx] & b)
only_bv_implies(flatten_constraint(cons))
>> [ (~a) -> AND([IV0 == 0, b]), (a) -> AND([IV0,b]), [arr[0],arr[1],arr[2]][idx] == IV0]
 


```

**Comment by tias** [comment]
We had shortly dsicussed the latter in person.

The real issue is that an Element of a an array that is all Boolean, should be a Boolean expression (so its .is_bool() should be true. (This is btw a fantastic reason why it was good that we decided that 'is_bool()' is a property, and not a subclassing into BoolExpr and NumExpr)

Anyway, if we make Element detect whether it is Bool or not, interesting things happen in unexpected ways... see #128
Now an Element() can be a top-level constraint, so ortools tries to decompose it...

What now? Should we special-case in the sovlers that a top-level element should an Element(arr, idx) == True solver constraint? Or should this be in a transformation rule? 

Do we even want this? Should the user not write `cons = a == ((arr[idx] == 1) & b)`? Like in who killed agatha...

I wonder if solvers are actually really capable of handling bool elements (other than treating them as ints). So... do we really want to support arr[idx] as Boolean expression?


[note that all of this is not central to the original question: should bounds computation be part of flatten (current status), of a separate transformation, or of the expressions themselves (in the latter case, globals can also compute their lb/ub without needing to modify flatten/the transformatoin like we now do for max/min/sum) -- actually, we DONT do that for max/min/element, we make an intvar with +max_int -max_int, which is rather stupid and can break solvers... so the original issue deserves a further discussion on its own!]

**Comment by tias** [comment]
OK so for now 'Element' remains an Integer Expression, meaning that what you what you want to achieve should be as:
```
cons  = (arr[idx] == 1)
```
or even
```
cons  = (arr[idx] == True)
```

Then everything works as expected, including reification and the like (e.g. `cons = a == ((arr[idx] == 1) & b)`.

So I am taking the 'bug' label of this issue.

The original issue remains, bounds computation (which are the toughest bugs to catch) are currently in `get_or_make_var()` of flatten, but they could be taken out:

* In flatten:
  + can keep current code

* In a new transformatoin:
 + can test separately

* In the Operator/Global objects:
  + can test separately
  + can define lb/ubs for 'new' global constraints without changing the transformations (incl pure user code)
  - may add quite some code to our generic (and lightweight) Expression objects

To be further discussed or tried... (non-urgent)

**Comment by IgnaceBleukx** [comment]
I think adding the code to compute bounds in the Expression objects would be easiest I think.
As one of our design choices is to not change the arguments in an Expression object, we could lazyily compute the bounds of an expression and then memoize it in the object to save computation next time `bounds()` is called. (the current implementation breaks SCIP, will mention it in pull request)

**Comment by tias** [comment]
Multiple of the fuzzer bugs show that indeed min_int/max_int breaks solvers, so we need tight bound computations for all expressions.

The best course of action is indeed a new Expressions.bounds() function (overloadable), that then returns the (lb,ub) of that expression.

Most of the logic (except for the globals, which is the crucial missing part) is implemented in `get_or_make_var()` in transformations/flatten:
https://github.com/CPMpy/cpmpy/blob/master/cpmpy/transformations/flatten_model.py#L284
